# Don't have a consumer key? Register your app in https://apps.twitter.com/app/new
# and they'll provide it to you
Twitter:
    consumer_key:        "YOUR_CONSUMER_KEY"
    consumer_secret:     "YOUR_CONSUMER_SECRET"
    access_token:        "YOUR_ACCESS_TOKEN"
    access_token_secret: "YOUR_TOKEN_SECRET"  